### PR TITLE
Updating Travis to see if it builds

### PR DESCRIPTION
**Pull request by concatime**
This is just a **test** to check if my modification alouds Travis to build.
https://stackoverflow.com/a/42141358
https://travis-ci.org/ivmai/libatomic_ops/jobs/304891407#L1137

### CODE REVIEW

**Comment by concatime** [comment]
Obviously, there is no gold linker in Mac OS.
https://stackoverflow.com/a/22088116

**Comment by concatime** [comment]
Actually, only `osx` based systems are failing. Can we ensure to use `gold` only if it's `linux` or not `osx`?

**Comment by ivmai** [comment]
I don't understand what are you asking for. Add tests with gold linker? is there any issue?

**Comment by concatime** [comment]
In the master branch, the build number `#254.26` is [failing](//travis-ci.org/ivmai/libatomic_ops/builds/304891335) because of [`/usr/bin/ld: unrecognized option '--push-state'`](//travis-ci.org/ivmai/libatomic_ops/jobs/304891407#L1137). Now, using my edit, the job is builing just [fine](//travis-ci.org/ivmai/libatomic_ops#ember1946) when using the gold linker, as mentioned [here](//stackoverflow.com/a/42141358). So, I had the idea to migrate to gold linker on linux jobs, is it possible?

**Comment by ivmai** [comment]
Thank you. See 40a49c9

**Pull request closed without merging**
