### PR TITLE
Fix tests for AArch64 ILP32

### PR DESCRIPTION
**Pull request by Kelledin**
As of 7.6.6, the current testsuite crashes and burns on AArch64 using ILP32 ABI:
 * test_atomic fails with a SIGBUS and appears to leave a corrupted stack frame.  (Or gdb is misreading the stack frame; I had to patch it to understand ILP32, after all.)
 * test_atomic_general fails too, though without a SIGBUS.
 * the testsuite then appears to hang indefinitely.

This appears to be due to the AArch64 routines using doubleword-size ldxp/stxp even in ILP32 mode.  The double_ptr_storage data type is missized for this case and doesn't satisfy alignment requirements (hence the SIGBUS).  If I switch the offending instructions to the 32-bit wordsize variant, the tests pass.  Someone with better knowledge of these routines (and AArch64 assembly in general) might want to review these for correctness.

Also, some might consider other solutions more graceful than scattering #ifdef's all over the code.  I considered writing a macro to abstract the register names, but I'm not sure it would be any nicer, and I'm hesitant to pollute the preprocessor's namespace.  I'm open to suggestions though.

### CODE REVIEW

**Comment by ivmai** [comment]
Is it possible to replace
ldaxp  %w0, %w1, %2
with
ldaxpw  %0, %1, %2

**Comment by ivmai** [comment]
Also, have you tested libatomic_ops for ilp32 with -D AO_AARCH64_ASM_LOAD_STORE_CAS passed to cflags?

BTW. Which gcc version do you use?

**Comment by ivmai** [comment]
> Is it possible to replace "ldaxp %w0, %w1, %2" with "ldaxpw %0, %1, %2"

Error: unknown mnemonic `ldxpw' -- `ldxpw x3,x2,[x1]'

**Comment by Kelledin** [comment]
> I'll review the patch.
> BTW. Is it possible (just in case you know) to download the toolchain and do cross-compilation on Travis CI like we do for aarch64: https://travis-ci.org/ivmai/libatomic_ops/jobs/445461574 ?

Building a cross-compiler is certainly possible (it's how I buildstrapped my ILP32 environment).  Stock Linux kernel and glibc do not support ILP32 without significant patching though.  gcc needs some mild patching to fix part of the libsanitizer build on ILP32.  And gdb needs some patching to understand ILP32 as well, if you want to do any debugging.  If you like, I can pass along the patches I've collected.

As far as llvm/clang, last I knew, they support AArch64, but only with LP64 ABI.  I'm not sure how much interest they have in ILP32, given its current niche status.

I assume you would run the unit-tests in a qemu system image?  I'm currently doing all my AArch64 work on a SolidRun MacchiatoBin board (I used to have access to a ThunderX system, but no longer :-( )

> Also, have you tested libatomic_ops for ilp32 with -D AO_AARCH64_ASM_LOAD_STORE_CAS 
> passed to cflags?
> 
> BTW. Which gcc version do you use?

I just added -DAO_AARCH64_ASM_LOAD_STORE_CAS to my build flags, with no obvious change in the build+test results.  OTOH I don't see that it activates any new codepaths, unless I were to build with clang (see above).

My current devtool set is Linux 4.16.18 (patched for ILP32), glibc-2.28 (patched for ILP32), binutils-2.31.1 (mostly stock), gcc-8.2.0 (patched for ILP32 libsanitizer support), and gdb-8.2 (patched for ILP32).  Note that binutils and gcc don't do well built natively for aarch64-linux-gnu_ilp32: binutils fails a bunch of regression tests in this case, and I didn't even bother trying to build gcc like that.  I just build them for aarch64-linux-gnu (LP64-native) and set -mabi=ilp32 when I build ILP32 components.

> Error: unknown mnemonic ldxpw' -- ldxpw x3,x2,[x1]'

Yup, same result on my end.  Maybe that's a clang-specific mnemonic?

**Comment by ivmai** [comment]
> Is it possible (just in case you know) to download the toolchain and do cross-compilation on Travis CI.

I will use https://mirrors.edge.kernel.org/pub/tools/crosstool/files/bin/x86_64/8.1.0/x86_64-gcc-8.1.0-nolibc-aarch64-linux.tar.xz with -mabi=ilp32 added to clfags to test the compilation on Travis.

> I just added -DAO_AARCH64_ASM_LOAD_STORE_CAS to my build flags, with no obvious change in the build+test results.

Right, my fault. Could you please try to run tests with your patch and the following change:
#if !defined(__clang__) || defined(AO_AARCH64_ASM_LOAD_STORE_CAS)
->
#if 0

**Comment by Kelledin** [comment]
> Could you please try to run tests with your patch and the following change:
> #if !defined(**clang**) || defined(AO_AARCH64_ASM_LOAD_STORE_CAS)
> ->
> #if 0

Done.  All tests still passing.

**Pull request closed without merging**
